name: Libplanet benchmark (for merge commits)
on:
  push:
    branches-ignore:
      - "gh-pages"

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Benchmark.Net benchmarks
    continue-on-error: true
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Run benchmark
      run: dotnet run -p Libplanet.Benchmarks -c Release -- --exporters json --filter '*'

    - name: Store benchmark result
      uses: planetarium/github-action-benchmark@v1
      with:
        name: Benchmark.Net Benchmark
        tool: 'benchmarkdotnet'
        output-file-path: BenchmarkDotNet.Artifacts/results/Combined.Benchmarks.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        benchmark-data-dir-path: dev/bench/${{ github.ref_name }}/${{ matrix.os }}
        auto-push: true
